name: Build Linux Tools

on:
  push:
    branches: [tengine-lite]
    paths-ignore: 
    - 'doc/**'
    - 'README.md'
    - 'README_EN.md'
  pull_request:
    branches: [tengine-lite]
    paths-ignore: 
    - 'doc/**'
    - 'README.md'
    - 'README_EN.md'

jobs:
  linux-x64-cpu-tools:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: update
      run: |
        sudo apt-get update
        sudo apt-get install libprotobuf-dev protobuf-compiler
    - name: find lib
      run: |
        cp /usr/lib/x86_64-linux-gnu/libprotobuf.so.23 /home/runner/work/Tengine/
    - name: configure
      run: mkdir build && cd build && cmake -DTENGINE_BUILD_TESTS=OFF -DTENGINE_BUILD_CONVERT_TOOL=ON ..
    - name: build
      run: cmake --build build -j 2
    - name: Zip directory
      run: |
        cd /home/runner/work/Tengine/
        zip -r tools.zip Tengine
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: tools
        path: /home/runner/work/Tengine/tools.zip
